package Exercicio.enums;

public enum TipoExercicio {
    ABDUTORA,
    FLEXORA,
    SUPINORETO,
    SUPINOINCLINADO,
    LEVANTAMENTOTERRA,
    LEGPRESS,
    AGACHAMENTOCOMHALTER,
    AGACHAMENTOLIVRE,
    ROSCAHALTER,
    ROSCASCOTT,
    ABDOMINAL,
    PUXADAPULLLEY,
    AFUNDO,
    ELEVACAOPELVICA,
    PRANCHA,
    REMADA,
    CRUCIFIXO,
    ELEVACAOLATERAL,
    ELEVACAOFRONTAL,

}
